### ISSUE TITLE
Fish hatched dual equip does not work in the Crypt

### ISSUE THREAD

**Issue by pstalcup** [Kasekopf/loop-casual#1]

**Comment by Kasekopf** [comment]
8cb3611 should make the Crypt work, but there is an underlying issue in the outfit code somewhere.

**Comment by spaghetti-squash** [comment]
the `tryCape` function appends its inputs onto the end of the inputted array. The `Outfit.create()` method runs `outfit.equip()` in order of items' appearance in the Task's associated items. The `outfit.equip()` method assigns `weapon` to the first weapon inputted, and `off-hand` to the second. 

The simplest fix would be to use `.unshift()` in `tryCape` rather than `.push()`. A more complex but possibly more rewarding fix would be to allow `Task.equip` to specify slot-item pairs, although you would have to make `outfit.equip()` be able to account for that more complex logic. phccs has moved towards a slightly different setup as it used to--it stores outfits as Objects rather than as Maps, which may? make this easier?

I think switching to `unshift` is probably good enough. Although I'm also not entirely convinced fish hatchet beats carnivorous potted plant in the offhand for the cranny, so it may be a moot point. Still probably worth fixing in case that code gets recycled later on in life.

**Comment by Kasekopf** [comment]
Thanks for debugging this! I will take a crack at refactoring the outfit code more generally later today.
