### ISSUE TITLE
Failed to Spit in Defiled Nook

### ISSUE THREAD

**Issue by Pantocyclus** [Kasekopf/loop-casual#8]
Unsure of root cause - may be because of passives triggering and killing before we can act

To not mess around with the combat logic too much, we can probably do spiny -> toothy -> toothy to double our chances of spitting on the toothy

**Comment by Pantocyclus** [comment]
Had a run that failed in the nook again

Would it make sense to try spitting on either of the spiny skelelton or toothy sklelton, instead of just the latter?

**Comment by Kasekopf** [comment]
I added some setting on the outfit so that the potted plant won't be equipped during the Nook, which might help avoid the failure. I also added a spit on the spiny skeleton if the first spit on the toothy sklelton doesn't go off; it's a bit delicate, since we are trying to Spit+Nostalgia and so can't just spit the first monster.
