### ISSUE TITLE
Can't use skill #7288 (Asdon Martin: Spring-Loaded Front Bumper)

### ISSUE THREAD

**Issue by Kasekopf** [Kasekopf/loop-casual#9]
The script tried to use skill #7288 on turn [76] in the The Typical Tavern Cellar, but it failed. The previous usage of #7288 was on turn [45]. After some restarts, #7288 was successfully used on [81].

**Comment by Pantocyclus** [comment]
I faced the same issue as well.
Looking at my logs, the root cause is probably the code trying to use the Asdon banish on the Drunken Rat King, which according to the wiki is a boss and is thus not allowed.
The most naive solution is to simply equip a Space Trip safety headphones to (1) decrease the combat rate (if we aren't already equipping -combat% accessories), and (2) ensure that ML is <= 0 so we will never fight any Drunken Rat Kings.

**Comment by MrFizzyBubbs** [comment]
This also happens when executing Bat/Boss Bat and fighting a beefy bodyguard bat.

**Comment by Kasekopf** [comment]
When it happened to me, it looks like it was actually a drunken rat that it failed on. So I don't think -ML will help. For now, I will turn off runaways that banish in the cellar (i.e., asdon and bowling ball) and in the Boss Bat's Lair and see if that fixes thing (even though cosmic bowling ball did work fine in the cellar; stupid complicated game).

**Comment by Kasekopf** [comment]
Haven't seen this myself in 3 weeks since the most recent fix, so closing. Please reopen if it still occurs.
